/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZardoziRouteImport } from './routes/zardozi'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SequinRouteImport } from './routes/sequin'
import { Route as ReshamZariRouteImport } from './routes/resham-zari'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PearlWorkRouteImport } from './routes/pearl-work'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CrystalStoneRouteImport } from './routes/crystal-stone'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ZardoziRoute = ZardoziRouteImport.update({
  id: '/zardozi',
  path: '/zardozi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SequinRoute = SequinRouteImport.update({
  id: '/sequin',
  path: '/sequin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReshamZariRoute = ReshamZariRouteImport.update({
  id: '/resham-zari',
  path: '/resham-zari',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PearlWorkRoute = PearlWorkRouteImport.update({
  id: '/pearl-work',
  path: '/pearl-work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CrystalStoneRoute = CrystalStoneRouteImport.update({
  id: '/crystal-stone',
  path: '/crystal-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/crystal-stone': typeof CrystalStoneRoute
  '/industries': typeof IndustriesRoute
  '/pearl-work': typeof PearlWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/resham-zari': typeof ReshamZariRoute
  '/sequin': typeof SequinRoute
  '/services': typeof ServicesRoute
  '/zardozi': typeof ZardoziRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/crystal-stone': typeof CrystalStoneRoute
  '/industries': typeof IndustriesRoute
  '/pearl-work': typeof PearlWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/resham-zari': typeof ReshamZariRoute
  '/sequin': typeof SequinRoute
  '/services': typeof ServicesRoute
  '/zardozi': typeof ZardoziRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/crystal-stone': typeof CrystalStoneRoute
  '/industries': typeof IndustriesRoute
  '/pearl-work': typeof PearlWorkRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/resham-zari': typeof ReshamZariRoute
  '/sequin': typeof SequinRoute
  '/services': typeof ServicesRoute
  '/zardozi': typeof ZardoziRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/crystal-stone'
    | '/industries'
    | '/pearl-work'
    | '/portfolio'
    | '/process'
    | '/resham-zari'
    | '/sequin'
    | '/services'
    | '/zardozi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/crystal-stone'
    | '/industries'
    | '/pearl-work'
    | '/portfolio'
    | '/process'
    | '/resham-zari'
    | '/sequin'
    | '/services'
    | '/zardozi'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/crystal-stone'
    | '/industries'
    | '/pearl-work'
    | '/portfolio'
    | '/process'
    | '/resham-zari'
    | '/sequin'
    | '/services'
    | '/zardozi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CrystalStoneRoute: typeof CrystalStoneRoute
  IndustriesRoute: typeof IndustriesRoute
  PearlWorkRoute: typeof PearlWorkRoute
  PortfolioRoute: typeof PortfolioRoute
  ProcessRoute: typeof ProcessRoute
  ReshamZariRoute: typeof ReshamZariRoute
  SequinRoute: typeof SequinRoute
  ServicesRoute: typeof ServicesRoute
  ZardoziRoute: typeof ZardoziRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zardozi': {
      id: '/zardozi'
      path: '/zardozi'
      fullPath: '/zardozi'
      preLoaderRoute: typeof ZardoziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequin': {
      id: '/sequin'
      path: '/sequin'
      fullPath: '/sequin'
      preLoaderRoute: typeof SequinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resham-zari': {
      id: '/resham-zari'
      path: '/resham-zari'
      fullPath: '/resham-zari'
      preLoaderRoute: typeof ReshamZariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pearl-work': {
      id: '/pearl-work'
      path: '/pearl-work'
      fullPath: '/pearl-work'
      preLoaderRoute: typeof PearlWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crystal-stone': {
      id: '/crystal-stone'
      path: '/crystal-stone'
      fullPath: '/crystal-stone'
      preLoaderRoute: typeof CrystalStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CrystalStoneRoute: CrystalStoneRoute,
  IndustriesRoute: IndustriesRoute,
  PearlWorkRoute: PearlWorkRoute,
  PortfolioRoute: PortfolioRoute,
  ProcessRoute: ProcessRoute,
  ReshamZariRoute: ReshamZariRoute,
  SequinRoute: SequinRoute,
  ServicesRoute: ServicesRoute,
  ZardoziRoute: ZardoziRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
