/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZardoziRouteImport } from './routes/zardozi'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SequinRouteImport } from './routes/sequin'
import { Route as ReshamZariRouteImport } from './routes/resham-zari'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PearlWorkRouteImport } from './routes/pearl-work'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CrystalStoneRouteImport } from './routes/crystal-stone'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio.$category'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminPortfolioRouteImport } from './routes/admin/portfolio'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as PortfolioItemIdRouteImport } from './routes/portfolio.item.$id'

const ZardoziRoute = ZardoziRouteImport.update({
  id: '/zardozi',
  path: '/zardozi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SequinRoute = SequinRouteImport.update({
  id: '/sequin',
  path: '/sequin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReshamZariRoute = ReshamZariRouteImport.update({
  id: '/resham-zari',
  path: '/resham-zari',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PearlWorkRoute = PearlWorkRouteImport.update({
  id: '/pearl-work',
  path: '/pearl-work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CrystalStoneRoute = CrystalStoneRouteImport.update({
  id: '/crystal-stone',
  path: '/crystal-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const PortfolioItemIdRoute = PortfolioItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/crystal-stone': typeof CrystalStoneRoute
  '/industries': typeof IndustriesRoute
  '/pearl-work': typeof PearlWorkRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/resham-zari': typeof ReshamZariRoute
  '/sequin': typeof SequinRoute
  '/services': typeof ServicesRoute
  '/zardozi': typeof ZardoziRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/portfolio/item/$id': typeof PortfolioItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/crystal-stone': typeof CrystalStoneRoute
  '/industries': typeof IndustriesRoute
  '/pearl-work': typeof PearlWorkRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/resham-zari': typeof ReshamZariRoute
  '/sequin': typeof SequinRoute
  '/services': typeof ServicesRoute
  '/zardozi': typeof ZardoziRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/admin': typeof AdminIndexRoute
  '/portfolio/item/$id': typeof PortfolioItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/crystal-stone': typeof CrystalStoneRoute
  '/industries': typeof IndustriesRoute
  '/pearl-work': typeof PearlWorkRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/process': typeof ProcessRoute
  '/resham-zari': typeof ReshamZariRoute
  '/sequin': typeof SequinRoute
  '/services': typeof ServicesRoute
  '/zardozi': typeof ZardoziRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/portfolio/item/$id': typeof PortfolioItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/crystal-stone'
    | '/industries'
    | '/pearl-work'
    | '/portfolio'
    | '/process'
    | '/resham-zari'
    | '/sequin'
    | '/services'
    | '/zardozi'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/portfolio'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/users'
    | '/portfolio/$category'
    | '/admin/'
    | '/portfolio/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin-login'
    | '/contact'
    | '/crystal-stone'
    | '/industries'
    | '/pearl-work'
    | '/portfolio'
    | '/process'
    | '/resham-zari'
    | '/sequin'
    | '/services'
    | '/zardozi'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/portfolio'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/users'
    | '/portfolio/$category'
    | '/admin'
    | '/portfolio/item/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/crystal-stone'
    | '/industries'
    | '/pearl-work'
    | '/portfolio'
    | '/process'
    | '/resham-zari'
    | '/sequin'
    | '/services'
    | '/zardozi'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/portfolio'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/users'
    | '/portfolio/$category'
    | '/admin/'
    | '/portfolio/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ContactRoute: typeof ContactRoute
  CrystalStoneRoute: typeof CrystalStoneRoute
  IndustriesRoute: typeof IndustriesRoute
  PearlWorkRoute: typeof PearlWorkRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ReshamZariRoute: typeof ReshamZariRoute
  SequinRoute: typeof SequinRoute
  ServicesRoute: typeof ServicesRoute
  ZardoziRoute: typeof ZardoziRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zardozi': {
      id: '/zardozi'
      path: '/zardozi'
      fullPath: '/zardozi'
      preLoaderRoute: typeof ZardoziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequin': {
      id: '/sequin'
      path: '/sequin'
      fullPath: '/sequin'
      preLoaderRoute: typeof SequinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resham-zari': {
      id: '/resham-zari'
      path: '/resham-zari'
      fullPath: '/resham-zari'
      preLoaderRoute: typeof ReshamZariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pearl-work': {
      id: '/pearl-work'
      path: '/pearl-work'
      fullPath: '/pearl-work'
      preLoaderRoute: typeof PearlWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crystal-stone': {
      id: '/crystal-stone'
      path: '/crystal-stone'
      fullPath: '/crystal-stone'
      preLoaderRoute: typeof CrystalStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portfolio/item/$id': {
      id: '/portfolio/item/$id'
      path: '/item/$id'
      fullPath: '/portfolio/item/$id'
      preLoaderRoute: typeof PortfolioItemIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortfolioRouteChildren {
  PortfolioCategoryRoute: typeof PortfolioCategoryRoute
  PortfolioItemIdRoute: typeof PortfolioItemIdRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCategoryRoute: PortfolioCategoryRoute,
  PortfolioItemIdRoute: PortfolioItemIdRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ContactRoute: ContactRoute,
  CrystalStoneRoute: CrystalStoneRoute,
  IndustriesRoute: IndustriesRoute,
  PearlWorkRoute: PearlWorkRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ReshamZariRoute: ReshamZariRoute,
  SequinRoute: SequinRoute,
  ServicesRoute: ServicesRoute,
  ZardoziRoute: ZardoziRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
